"use client";

import { useState, type FormEvent } from "react";
import { inputClass, labelClass, submitClass } from "./formStyles";

interface ReviewResult {
  atsScore: number;
  matchScore: number;
  missingSkills: string[];
  strengths: string[];
  weaknesses: string[];
  model: string;
}

function ResultSection({ title, items }: { title: string; items: string[] }) {
  if (items.length === 0) return null;
  return (
    <div className="mt-4 border-t border-rule pt-3">
      <p className="font-mono text-xs uppercase tracking-[0.08em] text-ink-soft">{title}</p>
      <ul className="mt-1 list-inside list-disc text-sm text-ink-soft">
        {items.map((item) => (
          <li key={item}>{item}</li>
        ))}
      </ul>
    </div>
  );
}

export default function AIReviewForm({
  jobs,
}: {
  jobs: { id: string; title: string; company: string }[];
}) {
  const [jobId, setJobId] = useState(jobs[0]?.id ?? "");
  const [result, setResult] = useState<ReviewResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  if (jobs.length === 0) {
    return <p className="text-sm text-ink-soft">No published roles to review against yet.</p>;
  }

  async function handleSubmit(event: FormEvent) {
    event.preventDefault();
    setLoading(true);
    setError(null);
    setResult(null);
    try {
      const response = await fetch("/api/ai/resume-review", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ jobId }),
      });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error ?? "Request failed.");
      setResult(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="max-w-2xl">
      <form onSubmit={handleSubmit} className="flex flex-wrap items-end gap-3">
        <div className="min-w-[240px] flex-1">
          <label className={labelClass} htmlFor="jobId">
            Role
          </label>
          <select
            id="jobId"
            value={jobId}
            onChange={(event) => setJobId(event.target.value)}
            className={`${inputClass} mt-1`}
          >
            {jobs.map((job) => (
              <option key={job.id} value={job.id}>
                {job.title} — {job.company}
              </option>
            ))}
          </select>
        </div>
        <button type="submit" disabled={loading} className={submitClass}>
          {loading ? "Reviewing…" : "Run AI review"}
        </button>
      </form>

      {error && <p className="mt-4 text-sm text-weak">{error}</p>}

      {result && (
        <div className="mt-6 rounded-sm border border-rule bg-paper-raised p-4">
          <p className="font-mono text-[11px] uppercase tracking-[0.08em] text-ink-faint">
            Generated by Google {result.model}, from your resume text and this
            job&apos;s description
          </p>
          <div className="mt-3 grid grid-cols-2 gap-4">
            <div>
              <p className="font-mono text-xs uppercase tracking-[0.08em] text-ink-soft">
                ATS score
              </p>
              <p className="font-serif text-3xl font-semibold tabular-nums text-ink">
                {result.atsScore}
              </p>
            </div>
            <div>
              <p className="font-mono text-xs uppercase tracking-[0.08em] text-ink-soft">
                Match score
              </p>
              <p className="font-serif text-3xl font-semibold tabular-nums text-ink">
                {result.matchScore}
              </p>
            </div>
          </div>
          <ResultSection title="Missing skills" items={result.missingSkills} />
          <ResultSection title="Strengths" items={result.strengths} />
          <ResultSection title="Weaknesses" items={result.weaknesses} />
        </div>
      )}
    </div>
  );
}
