import type { Job } from "./types";

/**
 * Seed listings for the demo. Dates are fixed (not relative to "now") so the
 * Signal Score's "posted recently" check produces consistent, reviewable
 * results regardless of when this is viewed.
 */
export const SEED_JOBS: Job[] = [
  {
    id: "northwind-staff-platform-eng",
    title: "Staff Engineer, Platform",
    company: "Northwind Data",
    location: "Remote (US/EU)",
    mode: "remote",
    level: "lead",
    salaryMin: 175000,
    salaryMax: 215000,
    currency: "USD",
    tags: ["Go", "Kubernetes", "Distributed Systems", "Postgres"],
    description:
      "Northwind Data runs the ingestion pipeline behind our analytics product, processing roughly 40TB of event data a day. We're looking for a staff engineer to own the reliability and scaling of that pipeline as we move from a single-region deployment to a multi-region one over the next two quarters. You'll work closely with our SRE and data platform teams, and you'll have real influence over architecture decisions rather than just implementing someone else's spec. We keep meetings light: two standups a week, one planning session, and otherwise heads-down time.",
    responsibilities: [
      "Design and implement the multi-region failover strategy for the ingestion pipeline",
      "Set and enforce SLOs for pipeline latency and data completeness across teams",
      "Mentor two senior engineers currently rotating onto the platform team",
      "Review architecture proposals from other teams that touch shared infrastructure",
    ],
    requirements: [
      "7+ years building distributed backend systems in production",
      "Deep experience with Kubernetes operators or custom controllers",
      "Track record leading a multi-quarter infrastructure migration",
      "Comfortable writing Go; willing to learn our internal tooling in Rust",
    ],
    postedAt: "2026-06-28",
  },
  {
    id: "fieldstone-frontend-react",
    title: "Frontend Engineer (React)",
    company: "Fieldstone Labs",
    location: "Remote (Worldwide)",
    mode: "remote",
    level: "mid",
    salaryMin: 95000,
    salaryMax: 120000,
    currency: "USD",
    tags: ["React", "TypeScript", "Accessibility", "Design Systems"],
    description:
      "Fieldstone Labs builds scheduling software for independent healthcare clinics. Our frontend team owns a shared component library used across three internal products, and we're hiring a mid-level engineer to help extend it while shipping features in our main scheduling app. Most of our clinics' staff are not tech-savvy, so accessibility and plain-language error states aren't a nice-to-have here, they're the actual job. You'd be the fourth engineer on a team that ships in two-week cycles with a real retro at the end of each one.",
    responsibilities: [
      "Ship features in the scheduling app end-to-end, from design handoff to production",
      "Extend and document components in the shared design system library",
      "Pair with our one designer on accessibility passes for existing screens",
      "Triage and fix bugs reported by clinic staff through our support channel",
    ],
    requirements: [
      "3+ years with React in a production codebase",
      "Experience with WCAG-level accessibility work, not just theoretical knowledge",
      "Comfortable reading and writing TypeScript across a mid-sized codebase",
      "Has shipped something used by non-technical end users before",
    ],
    postedAt: "2026-06-30",
  },
  {
    id: "ledger-product-designer",
    title: "Product Designer",
    company: "Ledger & Co",
    location: "Boston, MA (Hybrid, 2 days/week)",
    mode: "hybrid",
    level: "mid",
    salaryMin: 92000,
    salaryMax: 118000,
    currency: "USD",
    tags: ["Product Design", "Figma", "Fintech", "Research"],
    description:
      "Ledger & Co is a 22-person team building reconciliation software for small accounting firms. We're hiring our second product designer to work directly with the founding team on a redesign of our core ledger view, which hasn't changed meaningfully in two years. You'll run your own customer interviews rather than working from a research team's handoff, since we don't have one yet. Expect a slower, more deliberate pace than a typical growth-stage startup: we ship redesigns after testing with real accountants, not on a sprint deadline.",
    responsibilities: [
      "Lead end-to-end redesign of the core ledger reconciliation view",
      "Run and synthesize customer interviews with practicing accountants",
      "Build and maintain our Figma component library alongside engineering",
      "Present design rationale directly to the two founders in weekly reviews",
    ],
    requirements: [
      "4+ years of product design experience, ideally on a data-dense product",
      "A portfolio that shows research-informed decisions, not just visuals",
      "Comfortable working without a dedicated research or content team",
      "Based within commuting distance of Boston for twice-weekly office days",
    ],
    postedAt: "2026-06-25",
  },
  {
    id: "meridian-devops-engineer",
    title: "DevOps Engineer",
    company: "Meridian Cloud",
    location: "Austin, TX (Onsite)",
    mode: "onsite",
    level: "senior",
    salaryMin: null,
    salaryMax: null,
    currency: "USD",
    tags: ["AWS", "Terraform", "CI/CD"],
    description:
      "Meridian Cloud provides managed hosting for mid-sized e-commerce companies. We're looking for a senior DevOps engineer to help modernize our deployment pipeline, which is currently a mix of Jenkins and hand-run scripts. You'd join a small infrastructure team of three and have a lot of latitude to propose and implement changes, including moving us toward infrastructure-as-code across the board.",
    responsibilities: [
      "Migrate existing Jenkins pipelines to a modern CI/CD platform",
      "Introduce Terraform for infrastructure currently managed by hand",
      "Reduce average deployment time, currently around 40 minutes",
    ],
    requirements: [
      "5+ years in a DevOps or infrastructure engineering role",
      "Hands-on experience with AWS and Terraform in production",
      "Has led at least one CI/CD migration before",
    ],
    postedAt: "2026-05-02",
  },
  {
    id: "brightpeak-growth-marketing",
    title: "Growth Marketing Manager",
    company: "BrightPeak",
    location: "Remote",
    mode: "remote",
    level: "mid",
    salaryMin: null,
    salaryMax: null,
    currency: "USD",
    tags: ["Growth", "Marketing", "Fast-Paced", "Self-Starter"],
    description:
      "BrightPeak is looking for a growth marketing manager to join our fast-paced, high-energy team. You'll wear many hats and help drive user acquisition across channels. Must be a self-starter with a growth mindset who thrives in ambiguity.",
    responsibilities: ["Own growth", "Drive acquisition", "Other duties as assigned"],
    requirements: ["Self-starter", "Growth mindset", "Thick skin"],
    postedAt: "2026-02-14",
  },
  {
    id: "vantage-junior-qa",
    title: "Junior QA Analyst",
    company: "Vantage Systems",
    location: "Columbus, OH (Onsite)",
    mode: "onsite",
    level: "junior",
    salaryMin: 19000,
    salaryMax: 21000,
    currency: "USD",
    tags: ["QA", "Manual Testing"],
    description:
      "Vantage Systems needs a junior QA analyst to help test our internal tools. Full-time position, onsite only, five days a week.",
    responsibilities: ["Run manual test cases", "Log bugs in the tracker"],
    requirements: ["Attention to detail"],
    postedAt: "2026-01-20",
  },
  {
    id: "solstice-software-engineer",
    title: "Software Engineer (Night Shift, Onsite Only)",
    company: "Solstice Tech Park",
    location: "Onsite Only",
    mode: "onsite",
    level: "mid",
    salaryMin: null,
    salaryMax: null,
    currency: "USD",
    tags: ["Full Stack", "Fast-Paced", "Rockstar"],
    description:
      "We are a leading company in the industry looking for a rockstar engineer. As part of our process, you'll complete an unpaid take-home assessment: a full working feature, built and deployed, due within 24 hours of receiving the brief. Reply-all to the entire hiring team once submitted so everyone can review simultaneously. Please note: any broken link in your submission will result in instant rejection, no exceptions. This is a high-pressure environment and we expect candidates to be available on short notice.",
    responsibilities: ["Complete assigned tasks", "Available on short notice", "Other duties as assigned"],
    requirements: ["Self-starter", "Comfortable in a fast-paced environment"],
    postedAt: "2026-06-29",
  },
  {
    id: "anchorpoint-customer-success",
    title: "Customer Success Associate",
    company: "Anchorpoint",
    location: "Remote (US)",
    mode: "remote",
    level: "junior",
    salaryMin: 52000,
    salaryMax: 62000,
    currency: "USD",
    tags: ["Customer Success", "SaaS", "Onboarding"],
    description:
      "Anchorpoint makes inventory software for independent bookstores. We're hiring our first dedicated customer success associate to handle onboarding calls and support tickets as our customer base grows past 300 stores. You'd report directly to the founder for now, with a plan to build out a small team under you within the year if things go well.",
    responsibilities: [
      "Run onboarding calls for new bookstore customers",
      "Triage and resolve support tickets within a one-business-day target",
      "Document common issues to build out our public help center",
    ],
    requirements: [
      "1-2 years in a customer-facing support or success role",
      "Comfortable being the first hire on a new function",
    ],
    postedAt: "2026-06-20",
  },
  {
    id: "buzzwave-marketing-intern",
    title: "Marketing Intern (Unpaid)",
    company: "BuzzWave Media",
    location: "Onsite",
    mode: "onsite",
    level: "junior",
    salaryMin: null,
    salaryMax: null,
    currency: "USD",
    tags: ["Marketing", "Social Media"],
    description:
      "Confidential client in the media space seeks an unpaid intern for an immediate start. Must be available to start the trial project tonight and submit by tomorrow morning. Great exposure opportunity for the right candidate.",
    responsibilities: ["Support the marketing team", "Other duties as assigned"],
    requirements: ["Available immediately"],
    postedAt: "2026-06-27",
  },
  {
    id: "cartography-data-analyst",
    title: "Data Analyst",
    company: "Cartography Insights",
    location: "Denver, CO (Hybrid, 3 days/week)",
    mode: "hybrid",
    level: "mid",
    salaryMin: 78000,
    salaryMax: 95000,
    currency: "USD",
    tags: ["SQL", "dbt", "Analytics"],
    description:
      "Cartography Insights helps mid-sized logistics companies model their delivery networks. We're hiring a data analyst to join our small analytics team and take ownership of a handful of recurring reporting pipelines built in dbt, plus ad hoc analysis for our customer success team.",
    responsibilities: [
      "Maintain and extend existing dbt models for delivery network reporting",
      "Build ad hoc analyses requested by the customer success team",
      "Flag data quality issues upstream before they reach dashboards",
    ],
    requirements: [
      "2+ years working with SQL in a production analytics context",
      "Some exposure to dbt or a similar transformation tool",
    ],
    postedAt: "2026-06-18",
  },
  {
    id: "rivergate-fullstack-senior",
    title: "Full-Stack Engineer",
    company: "Rivergate Labs",
    location: "Remote (US)",
    mode: "remote",
    level: "senior",
    salaryMin: 140000,
    salaryMax: 165000,
    currency: "USD",
    tags: ["Node.js", "React", "Postgres", "GraphQL"],
    description:
      "Rivergate Labs builds compliance tracking software for construction firms. We're hiring a senior full-stack engineer to work across our Node.js API and React frontend, with a focus on a permitting workflow feature that's currently our top customer request. You'd work in a team of five, with direct access to the two engineers who built the original system.",
    responsibilities: [
      "Design and ship the new permitting workflow feature end-to-end",
      "Work across the Node.js API and React frontend as needed",
      "Pair with newer engineers on the team during onboarding",
      "Participate in an on-call rotation covering roughly one week in five",
    ],
    requirements: [
      "5+ years of full-stack experience with Node.js and React",
      "Experience with GraphQL APIs in production",
      "Comfortable being part of a small on-call rotation",
    ],
    postedAt: "2026-04-10",
  },
];
